### ISSUE TITLE
Feature Request: Access to column names

### ISSUE THREAD

**Issue by jayniz** [fieldbook/api-docs#2]
It would be great to get access to column names and more metadata of sheets.

**Comment by jasoncrawford** [comment]
You mean you'd like to be able to query a sheet and see what fields it has? Can you describe a scenario where you would need that? We've been assuming that for most uses the fields are fixed and you know what they are.

**Comment by jayniz** [comment]
Exactly that - would be useful for me to know some things about the columns (type, for example). Also, it would be great if they had an identifier independent from the column name. 

Edit: same goes for the id column. We use "human readable" short ids in our sheets, so that when referencing a row from another sheet, we can identify the right row from its id (so the id is actually more like a short name or slug, in our case). This works nice when somebody edits a sheet. If I remember correctly, changing the id of a row also updates other rows referencing it. For an external service syncing sheets, though, it would be great to have stable ids for rows, so treating the id column in a sheet more like a unique, but mutable key.

**Comment by jasoncrawford** [comment]
What's the scenario where the columns and types aren't fixed and known ahead of time? Can you describe the context around the use case?

Regarding stable ids for records: Each record should have an `id` attribute which is a short integer ID. This is permanent. Note that if you have a column named "ID", that column will shadow the `id` attribute. (We haven't solved the shadowing problem yet.)

**Comment by DeanWard** [comment]
I can provide an example use case. We have a dialling system for our agents to call targets and engage with them / collect information, deliver sales pitches, etc. The system has a flexible metadata system for projects so that a project that, for example, targets the fleet sector can contain information about a company's fleet size and makeup but a project that targets prospects for loans would contain information about creditworthiness, turnover, employee counts, etc.

Our importer is able to deal with multiple data sources and does a good job of transforming information automatically - I'd love to be able to extend that to yank data in from FB in the same flexible way so an API endpoint to query column information would be a huge help there.

**Comment by jasoncrawford** [comment]
This is done! Sheets and fields can now be retrieved using the Fieldbook metadata API: https://github.com/fieldbook/api-docs/blob/master/metadata.md

Thanks all for the feedback.

**Comment by mlrawlings** [comment]
@jasoncrawford This is great! 🎉 

However, it doesn't look like linked columns specify which sheet they are linked to?

I would expect a field object to also contain a `linkedSheet` property (or something similar) which is the id of sheet this field is linked to, if fieldType=link

_EDIT: Opened a separate issue #24_
